// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Startly.Context;

#nullable disable

namespace Startly.Migrations
{
    [DbContext(typeof(StartlyContext))]
    partial class StartlyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Startly.Domains.Atuacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Atuacao", (string)null);
                });

            modelBuilder.Entity("Startly.Domains.Startup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("EnumTicket")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("RespCadastro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SiteStartup")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("metas")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.Property<int>("qtdeFuncionario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Startup", (string)null);
                });

            modelBuilder.Entity("Startly.Domains.StartupAtuacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtuacaoId")
                        .HasColumnType("int");

                    b.Property<int>("StartupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtuacaoId");

                    b.HasIndex("StartupId");

                    b.ToTable("StartupAtuacao", (string)null);
                });

            modelBuilder.Entity("Startly.Domains.StartupContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Contato")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("StartupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartupId");

                    b.ToTable("StartupContato", (string)null);
                });

            modelBuilder.Entity("Startly.Domains.StartupImagens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StartupId")
                        .HasColumnType("int");

                    b.Property<int>("TipoImagem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartupId");

                    b.ToTable("StartupImagens", (string)null);
                });

            modelBuilder.Entity("Startly.Domains.StartupVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LinkVideo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StartupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartupId");

                    b.ToTable("StartupVideo", (string)null);
                });

            modelBuilder.Entity("Startly.Domains.StartupAtuacao", b =>
                {
                    b.HasOne("Startly.Domains.Atuacao", "Atuacao")
                        .WithMany("atuacaos")
                        .HasForeignKey("AtuacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Startly.Domains.Startup", "Startup")
                        .WithMany("atuacaos")
                        .HasForeignKey("StartupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atuacao");

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("Startly.Domains.StartupContato", b =>
                {
                    b.HasOne("Startly.Domains.Startup", "Startup")
                        .WithMany("contatos")
                        .HasForeignKey("StartupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("Startly.Domains.StartupImagens", b =>
                {
                    b.HasOne("Startly.Domains.Startup", "Startup")
                        .WithMany("imagens")
                        .HasForeignKey("StartupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("Startly.Domains.StartupVideo", b =>
                {
                    b.HasOne("Startly.Domains.Startup", "Startup")
                        .WithMany("Videos")
                        .HasForeignKey("StartupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("Startly.Domains.Atuacao", b =>
                {
                    b.Navigation("atuacaos");
                });

            modelBuilder.Entity("Startly.Domains.Startup", b =>
                {
                    b.Navigation("Videos");

                    b.Navigation("atuacaos");

                    b.Navigation("contatos");

                    b.Navigation("imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
